[tool.poetry]
name = "eoread"
version = "0.3-dev"
license = "Apache 2.0"
description = "Modular implementation of satellite data input/output relying on xarray."
authors = ["HYGEOS Team"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10"
rasterio = "*"
dask = "*"
numpy = "<2"
shapely = "*"
scipy = "*"
netcdf4 = "*"
pyproj = "*"
lxml = "*"
h5netcdf = "*"
xarray = "*"
pyepr = "*"
rioxarray = "*"
core = {git = "https://github.com/hygeos/core.git"}

[tool.poetry.group.dev.dependencies]
pytest = "*"
pytest-html = "*"
pytest-xdist = "*"
matplotlib = "*"
# h5netcdf = "*"
pyhdf = "*"
h5py = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
